name: Build & Test

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/**.md'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**/**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['14']
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: '14'
            os: windows-latest
          - node-version: '14'
            os: ubuntu-latest
            coverage: true
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install --frozen-lockfile
      - run: yarn test
        if: ${{ !matrix.coverage }}
      - run: yarn test:coverage
        if: ${{ matrix.coverage }}
      - name: build
        run: yarn build
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.coverage }}
